#默认使用配置
spring:
  profiles:
    active: dev

#公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
mybatis:
  typeAliasesPackage: com.example.demo.model
  mapperLocations: classpath:com.example.demo.mapper/*.xml



---

#开发配置
spring:
  profiles: dev

  datasource:
    url: jdbc:mysql://112.126.66.252:3306/mysql
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource

logging:
  level:
    org.springframework.web: DEBUG        ##Spring框架中的日志级别
    com.example.demo: DEBUG    ##自己项目包名下的日志级别
    com.example.demo.dao: DEBUG    ##自己项目包名下的日志级别
